version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www/html:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: on-failure
    env_file:
      - .env
