CREATE USER IF NOT EXISTS 'PHP_USER'@'172.18.0.0/255.255.0.0' IDENTIFIED BY 'QW48BSCO7W';
CREATE DATABASE IF NOT EXISTS phpVoting;
GRANT ALL PRIVILEGES ON phpVoting.* TO 'PHP_USER'@'172.18.0.0/255.255.0.0' IDENTIFIED BY 'QW48BSCO7W';
FLUSH PRIVILEGES;
USE phpVoting;
CREATE TABLE IF NOT EXISTS votes(vote_id INTEGER PRIMARY KEY AUTO_INCREMENT, vote_target VARCHAR(255), ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(user_id INTEGER PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255), hash VARCHAR(255));
CREATE TABLE IF NOT EXISTS custom_field(field_id INTEGER PRIMARY KEY AUTO_INCREMENT, field_name VARCHAR(255), field_value VARCHAR(1024));

INSERT INTO users (username, hash) SELECT 'admin', '$2y$10$NL5UtzFU5ICX9oZX9u9EcuEYxngkhRTO6aR4deayKClHmM.psBxxW' WHERE NOT EXISTS(SELECT * FROM users);

